### PR TITLE
Feature/blocking

### PR DESCRIPTION
**Pull request by gkevinyen5418**
Blocks the start_worker process from exiting.
Otherwise, we seems to have some issues with slurm.

### CODE REVIEW

**Comment by FrankLeeeee** [comment]
did you launch multiple processes with srun?

**Comment by FrankLeeeee** [comment]
did you launch multiple processes with srun?

**Comment by gkevinyen5418** [comment]
`start_worker.py` uses `Popen` at multiple places

https://github.com/hpcaitech/scalable-ml/blob/3d06076a94a15916d4ab5f871b32ef73fed38dea/scalableml/start_worker.py#L52

https://github.com/hpcaitech/scalable-ml/blob/3d06076a94a15916d4ab5f871b32ef73fed38dea/scalableml/start_worker.py#L89

**Comment by gkevinyen5418** [comment]
If we run the experiment script [example/torch_vision/exp.sh](https://github.com/hpcaitech/scalable-ml/blob/5cdd9b09ed0c66087f8bdc7d31c63f23e116b7bf/example/torch_vision/exp.sh#L16) with
```
idev
bash exp.sh
```
then

```bash
# Failure
srun --nodes=1 --ntasks=1 -w "$head_node" \
    start_worker --head --headport $port &> logs/head.log &

# OK
start_worker --head --headport $port &> logs/head.log &

# also OK
srun --nodes=1 --ntasks=1 -w "$head_node" \
    start_worker --head --block --headport $port &> logs/head.log &
```
I haven't tested it with `sbatch` yet, but I suspect the results should be similar

**Comment by gkevinyen5418** [comment]
Closed as we want to improve our workflow.

**Pull request closed without merging**
